version: 2
jobs:
  build:
    working_directory: ~/scalar-jepsen

    docker:
      - image: circleci/clojure:lein-2.9.1

    environment:
      JVM_OPTS: -Xmx3200m
      LEIN_ROOT: nbd

    steps:
      - checkout

      - restore_cache:
          key: scalar-jepsen-{{ checksum "cassandra/project.clj" }}-{{ checksum "scalardb/project.clj" }}-{{ checksum "scalardl/project.clj" }}

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: scalar-jepsen-{{ checksum "cassandra/project.clj" }}-{{ checksum "scalardb/project.clj" }}-{{ checksum "scalardl/project.clj" }}

      - run:
          name: Run tests for cassandra
          command: |
            cd cassandra
            lein test
